### Методичка 1
**Задача 1.** Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:  
а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;    
Произведение AB и BA в данном случае невозможно, т к ни в одном из случаев количество столбцов 1ой матрицы не будет равно кол-ву строк 2ой

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;  
Возможно произведение С = AB, С будет размера 2х3


в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;  
Возможны оба варианта C=AB=(8x8), C1 = BA = (3x3)



г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .
Возможны оба варианта С = AB = (4x4), C1 = BA = (4x4)

**Задания 2, 3 и 4 рассчитаны вручную на листочке (см фото les2_1), ниже приведены решение через numpy для проверки полученного результата**

**Задача 2.** Найти сумму и произведение матриц A и B

In [1]:
import numpy as np

In [10]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица А: \n{A} \nМатрица В: \n{B}')

Матрица А: 
[[ 1 -2]
 [ 3  0]] 
Матрица В: 
[[ 4 -1]
 [ 0  5]]


In [20]:
print(f'A+B\n{A+B} \nA*B\n{np.dot(A,B)} \nB*A\n{np.dot(B, A)}')

A+B
[[ 5 -3]
 [ 3  5]] 
A*B
[[  4 -11]
 [ 12  -3]] 
B*A
[[ 1 -8]
 [15  0]]


**Задача 3.** Вычислить линейную комбинацию  3𝐴−2𝐵+4𝐶  для матриц A, B и C

In [23]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица А: \n{A} \nМатрица В: \n{B} \nМатрица C: \n{C}')

Матрица А: 
[[ 1  7]
 [ 3 -6]] 
Матрица В: 
[[ 0  5]
 [ 2 -1]] 
Матрица C: 
[[ 2 -4]
 [ 1  1]]


In [25]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

**Задание 4.** Дана матрица А. Вычислить  𝐴𝐴𝑇  и  𝐴𝑇𝐴 (матрицу корреляции и матрицу ковариаций)

In [28]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [30]:
AT = A.T
AT

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [32]:
corr_matrix = np.dot(A, AT)
corr_matrix

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [33]:
cov_matrix = np.dot(AT, A)
cov_matrix

array([[45,  0],
       [ 0, 14]])

### Методичка 2

**Задания методички выполнены на листочке (см приложенные фото les2_2 и 3), проверка произведена по функциям numpy**

**Задание 1.** Вычислить определитель

In [49]:
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(B)

180.0

In [51]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(C)

0.0

**Задание 3.** Доказать, что матрица вырожденная

In [53]:
# проверим определитель (должен быть равен 0)
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(A)

0.0

Определитель равен 0 -> значит матрица является вырожденной

**Задание 4.** Найти ранг матрицы

In [57]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Ранг матрицы А = {np.linalg.matrix_rank(A)}')

Ранг матрицы А = 2


In [58]:
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Ранг матрицы B = {np.linalg.matrix_rank(B)}')

Ранг матрицы B = 3
