**Задание 1.** Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей A

In [21]:
import numpy as np

In [22]:
A = np.array([[-1, -6], [2, 6]])
A

array([[-1, -6],
       [ 2,  6]])

$A = [[-1-lambda, -6]  [2, 6-lambda]])$   
найдем определитель  

lambda = l

$detA = (1-l)*(6-l) - ((-6)*2) = (-6-6*l + l^2 + l) + 12 = l^2 - 5*l - 6 + 12 = l^2-5*l+6 =0$  
$l_{1} = 2$  
$l_{2} = 3$  

Найдем собственные векторы  
1) при $l_1=2  $  
$A*(x_1, x_2) = l_1(x_1, x_2)  $  

составим систему уравнений  
$-1*x_1 - 6*x_2 = 2*x_1  $
$2*x_1 + 6*x_2 = 2*x_2 $ 

$-6*x_2 = 3*x_1  $
$2*x_1 = - 4*x_2 $ 

Из обоих уравнений получается, что:
$x_1 = - 2*x_2$

Пусть $x_{2}= 1$, тогда $x_{1}$ = -2 и собственный вектор будет (-2,1)

2) при $l_2=3 $   
$A*(x_1, x_2) = l_2(x_1, x_2)$    

Составим систему уравнений  
$-1*x_1 - 6*x_2 = 3*x_1 $   
$2*x_1 + 6*x_2 = 3*x_2  $

$-6*x_2 = 4*x_1$   
$2*x_1 = -3*x_2$

$-3*x_2 = 2*x_2$  
$2*x_1 = -3*x_2$ 

Из обоих уравнений получаем:
$x_1 = -3/2*x_2$  

Пусть $x_2 = 2, -> x_1 = -3$ и собственный вектор = (-3,2)  

Итого собственные значения = 2 и 3,  
Собственные векторы = (-2,1) и (-3, 2)

In [23]:
# Проверим собственные значения
v,w = np.linalg.eig(A) 
v

array([2., 3.])

**Задание 2.** Дан оператор поворота на 180 градусов, задаваемый матрицей A. Показать, что любой вектор является для него собственным.

In [24]:
A = np.array([[-1, 0], [0, -1]])
A

array([[-1,  0],
       [ 0, -1]])

$A = [[-1-lambda, 0]  [0, -1-lambda]])$   
найдем определитель  

lambda = l

Найдем detA и приравниваем к 0
$(-1-l)^2 - 0 = 0 $  
$(-1-l)^2 = 0$  
$-1-l = 0$  
$l = 1 $  

Найдем собственные векторы.   
$A*(x_1, x_2) = -1* (x_1, x_2)$  

$-1*x_1 + 0*x_2 = -x_1$  
$0*x_1 -1*x_2 = -1*x_2$  

$-x_1 = -x_1$  
$-x-2 = -x_2$  

Можно сделать вывод, что любой ненулевой вектор будет собственным для оператора А, чтд

**Задание 3.** Пусть линейный оператор задан матрицей A. Установить, является ли вектор  𝑥=(1,1)  собственным вектором этого линейного оператора.

In [25]:
A = np.array([[1, 1], [-1, 3]])
A

array([[ 1,  1],
       [-1,  3]])

Решим систему уравнений  
$x_1 = 1$  
$x_2 = 2$  

$A*(1,1) = l * (1,1)$  

1*1+1*1 = l*1  
-1*1 + 3*1 = l*1  

из обоих уравнений следует, что l = 2, значит вектор (1,1) является собственным

**Задание 4.** Пусть линейный оператор задан матрицей A. Установить, является ли вектор  𝑥=(3,−3,−4)  собственным вектором этого линейного оператора.

In [26]:
A = np.array([[0, 3, 0], [3, 0,0 ], [0, 0, 3]])
A

array([[0, 3, 0],
       [3, 0, 0],
       [0, 0, 3]])

Решим систему уравнений  

$x_1 = 3, x_2 = -3, x_3 = -4$  
$A*(3,-3,-4) = l*(3,-3,-4)  $

$0*3+3*(-3)+0*(-4) = 3*l$  
$3*3 + 0*(-3) + 0*(-4) = l*(-3)$  
$0*3+0*(-3)+3*(-4) = l*(-4)$  

$-9 = l*3$  
$9 = l*(-3)$  
$-12 = l*(-4)$  

$l=-3$  
$l=-3$  
$l = 3$  

Решив систему уравнений, мы не получаем единственное число лямбда , значит вектор х в данном случае не является собственным вектором линейного оператора А