### Методичка 1

**Задание 1.** Решить систему уравнений методом Гаусса.   
Решено на листочке см фото


**Задание 2.** Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений

In [9]:
# a)
import numpy as np
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A_wide = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_wide)

True

In [11]:
n = 3 #количество переменных
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_wide) == n

True

Вывод: система совместна и имеет единственное решение

In [20]:
# б)
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
A_wide = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_wide)

False

In [21]:
print(f'Ранг матрицы А = {np.linalg.matrix_rank(A)},\nранг расширенной матрицы А= {np.linalg.matrix_rank(A_wide)}')

Ранг матрицы А = 1,
ранг расширенной матрицы А= 2


Вывод: система несовместна, т е не имеет решений

In [23]:
#в)
A = np.array([[1, 2, 5], [3, 1, -8]])
A_wide = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_wide)

True

In [26]:
n = 3
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_wide)== n

False

In [27]:
np.linalg.matrix_rank(A)

2

Вывод: ранг матрицы = рангу расширенной матрицы , но меньше количества переменных, значит система совместна и имеет бесконечное множество решений

**Задание 3.** Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей A_wide

In [33]:
A_wide = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
print(f'Матрица А расширенная:\n{A_wide}\nМатрица А:\n{A}')

Матрица А расширенная:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Матрица А:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]


Сразу можно определить ранги:  
ранг A = 4  
ранг A_wide также = 4   
количество переменных также равно 4  

Система совместна и будет иметь единственное решение

**Задание 4.**  Дана система линейных уравнений, заданная расширенной матрицей. Найти соотношение между параметрами  𝑎 ,  𝑏  и  𝑐 , при которых система является несовместной.  
Задание решено на листочке( см фото)

### Методичка 2

**Задания решены на листочке (см фото).**