**Задание 1.** Найти с помощью NumPy SVD для матрицы A

In [77]:
import numpy as np

In [78]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
print(f'Матрица А: \n{A}')

Матрица А: 
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [79]:
#Найдем сингулярное разложение матрицы А
U, s, W = np.linalg.svd(A)
D = np.zeros_like(A, dtype = float)
D[np.diag_indices(3)] = s

print(f'Матрица U: \n{U}, \n\nДиагональная матрица D: \n{D}, \n\nМатрица  V: \n{W}')

Матрица U: 
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]], 

Диагональная матрица D: 
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]], 

Матрица  V: 
[[ 0.07116451  0.71702467  0.69340553]
 [-0.36737824  0.66514082 -0.65009301]
 [-0.92734505 -0.20847855  0.31075368]]


**Задание 2.** Найти для матрицы А норму а)Евклида и б)Фробениуса

In [80]:
#Евклидова норма при существующем сингулярном разложении будет равна первому(наибольшему) элементу диагональной 
#матрицы D или первому элементу массива s
norm_e = s[0]

#Норму Фробениуса найдем с помощью встроенной функции numpy.linalg
norm_f = np.linalg.norm(A, ord = 'fro')
print(f'Норма Евклида = {norm_e}, Норма Фробениуса = {norm_f}')

Норма Евклида = 8.824868854820444, Норма Фробениуса = 11.045361017187261


In [81]:
# В качестве проверки рассчитаем норму Фробениуса вручную
from math import sqrt
norm_f_1 = sqrt(sum(D[np.diag_indices(min(D.shape))]**2))
norm_f_1

11.045361017187263

In [82]:
# Проверка, норма Евклида должна быть меньше нормы Фробениуса
norm_e < norm_f

True